"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
// import Preloader from "@/components/Preloader";
import { metadata } from "./metaData";
import NextModal from "@/components/NextModal";




// export const metadata = {
//   title: "Valley Journey",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(true);

useEffect(() => {
  // Simulate data fetching delay
  const timer = setTimeout(() => {
    setLoading(false);
  }, 2000);

  // Clear timeout on component unmount
  return () => clearTimeout(timer);
}, []);
  return (
    <html lang="en">
    <head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
    </head>
    <body>
      {/* {loading ? <Preloader /> : <div></div>} */}
      <Header />
      <main>{children}</main>
      <Footer />
      <NextModal/>

    </body>
  </html>
  );
}
